/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neopi_demo_jni_JniUtils */

#ifndef _Included_com_neopi_demo_jni_JniUtils
#define _Included_com_neopi_demo_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neopi_demo_jni_JniUtils
 * Method:    secondTest
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_neopi_demo_jni_JniUtils_secondTest
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_neopi_demo_jni_JniUtils
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_neopi_demo_jni_JniUtils_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
